#!/bin/bash

CUR_DIR=`pwd`

ENDPOINT="https://api.chatwork.com/v1"
SAVE_API_CODE=$HOME/.chatwork
SAVE_ROOM_ID=$HOME/.chatwork.room

usage() {
    echo "Usage: $0 [ -h ] [ -i ] [ -s ] [ -c api token ] [-r room_id] {get-rooms|get-room|get-me|get-my-status|post-mes} params..."
    echo "   -s : silent mode"
    echo "   -i : interactive mode ( when \"post-mes\" )"
    echo "   params (when \"post-mes\") : message"
}

while getopts hc:r:ois OPT
do
    case $OPT in
        h)  usage
            exit 0
            ;;
        c)
            API_CODE="$OPTARG"
            ;;
        r)
            ROOM_ID="$OPTARG"
            ;;
        o)
            IS_ONESHOT="1"
            ;;
        i)
          IS_INTERACTIVE_MODE="1" # Interactive mode ( when post-mes )
            ;;
        s)
          IS_SILENT_MODE="1"
            ;;
        \?) usage
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$API_CODE" = "" ];then
    if [ -s $SAVE_API_CODE ];then
        API_CODE=`cat $SAVE_API_CODE`
    else
        usage
        exit 1
    fi
fi

if [ "$1" = "" ]; then
    usage
    exit 1
fi

CW_API_CMD="$1"
CW_PARAMS="$2"

gen_curl_cmd() {
    FUNC_PARAM1=$1
    FUNC_PARAM2=$2

    case $FUNC_PARAM1 in
        get-me)
            API_METH="GET"
            API_PATH="me"
            ;;
        get-rooms)
            API_METH="GET"
            API_PATH="rooms"
            ;;
        get-my-status)
            API_METH="GET"
            API_PATH="my/status"
            ;;
        "post-mes"|"get-room")
            if [ "$ROOM_ID" = "" ];then
                if [ -s $SAVE_ROOM_ID ];then
                    ROOM_ID=`cat $SAVE_ROOM_ID`
                else
                    usage
                    exit 1
                fi
            fi
            if [ "$ROOM_ID" = "" ];then
                usage
                exit 1
            fi

            if [ "$FUNC_PARAM1" = "get-room" ];then
                API_METH="GET"
                API_PATH="rooms/$ROOM_ID"
            elif [ "$FUNC_PARAM1" = "post-mes" ];then
                API_METH="POST"
                API_PATH="rooms/$ROOM_ID/messages"
            fi

            ;;
        \?) usage
            exit 1
            ;;
    esac

    CURL_HD="-X $API_METH"
    if [ "$FUNC_PARAM1" = "post-mes" ];then
        API_POST_MES=`echo "$FUNC_PARAM2" | ruby -r uri -ne 'print URI.escape $_'`
        CURL_HD="$CURL_HD -d \"body=$API_POST_MES\""
    fi

    CURL_API_CODE="-H \"X-ChatWorkToken: $API_CODE\""

    CURL_CMD="curl -s \
     $CURL_HD \
     $CURL_API_CODE \
     $ENDPOINT/$API_PATH"

    eval $CURL_CMD
}

if [ "$CW_API_CMD" = "post-mes" -a "$IS_INTERACTIVE_MODE" = "1" ];then
    CURL_RES=`gen_curl_cmd get-room $CW_PARAMS | jq ".name"`
    if [ "$CURL_RES" = "" ];then
        CW_PROMPT="$ROOM_ID"
    else
        CW_PROMPT="$CURL_RES"
    fi

    echo -n "$CW_PROMPT > "
    while read MES; do
        if [ "$MES" = "" ];then
            echo -n "quit? (enter quit)"
            read STOP_CHECK_INPUT
            if [ "$STOP_CHECK_INPUT" = "" ];then
                echo "quit"
                break
            fi
            echo -n "$CW_PROMPT > "
            continue
        fi
        gen_curl_cmd $CW_API_CMD "$MES" >/dev/null
        echo -n "$CW_PROMPT > "
    done
else
    CURL_RES=`gen_curl_cmd $CW_API_CMD $CW_PARAMS`
    if [ "$IS_SILENT_MODE" != "1" ];then
        type jq 2>&1 >/dev/null
        if [ $? -eq 0 ];then
            echo $CURL_RES | jq "."
        else
            echo $CURL_RES
        fi
    fi
fi

if [ "$IS_ONESHOT" != "1" ];then
    if [ "$API_CODE" != "" ];then
        echo "$API_CODE" > $SAVE_API_CODE
    fi
    if [ "$ROOM_ID" != "" ];then
        echo "$ROOM_ID" > $SAVE_ROOM_ID
    fi
fi

exit 0
