#!/bin/bash

CUR_DIR=`pwd`

ENDPOINT="https://api.chatwork.com/v1"

usage() {
    echo "Usage: $0 [ -h ] [ -c api token ] {get-rooms|get-me|get-my-status|post-mes} params..."
    echo "   when post-mes params : roomid message"
}

while getopts hc: OPT
do
    case $OPT in
        h)  usage
            exit 0
            ;;
        c)
            API_CODE="$OPTARG"
            ;;
        \?) usage
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$1" = "" ]; then
    usage
    exit 1
fi

CW_API_CMD="$1"

case $CW_API_CMD in
    get-me)
        API_METH="GET"
        API_PATH="me"
        ;;
    get-rooms)
        API_METH="GET"
        API_PATH="rooms"
        ;;
    get-my-status)
        API_METH="GET"
        API_PATH="my/status"
        ;;
    post-mes)
        if [ "$2" = "" -o "$3" = "" ];then
            usage
            exit 1
        fi
        API_METH="POST"
        API_PATH="rooms/$2/messages"
        API_POST_MES=`echo $3 | ruby -r uri -ne 'print URI.escape $_'`
        ;;
    \?) usage
        exit 1
        ;;
esac

CURL_HD="-X $API_METH"
if [ "$CW_API_CMD" = "post-mes" ];then
    CURL_HD="$CURL_HD -d \"body=$API_POST_MES\""
fi

CURL_API_CODE="-H \"X-ChatWorkToken: $API_CODE\""

CURL_CMD="curl -s \
 $CURL_HD \
 $CURL_API_CODE \
 $ENDPOINT/$API_PATH"

CURL_RES=`eval $CURL_CMD`

type jq 2>&1 >/dev/null
if [ $? -eq 0 ];then
    echo $CURL_RES | jq "."
else
    echo $CURL_RES
fi

exit 0
