#!/bin/bash

CUR_DIR=`pwd`

ENDPOINT="https://api.chatwork.com/v1"
SAVE_API_CODE=$HOME/.chatwork
SAVE_ROOM_ID=$HOME/.chatwork.room

usage() {
    echo "Usage: $0 [ -h ] [ -c api token ] [-r room_id] {get-rooms|get-me|get-my-status|post-mes} params..."
    echo "   when post-mes params : message"
}

while getopts hc:r:o OPT
do
    case $OPT in
        h)  usage
            exit 0
            ;;
        c)
            API_CODE="$OPTARG"
            ;;
        r)
            ROOM_ID="$OPTARG"
            ;;
        o)
            IS_ONESHOT="1"
            ;;
        \?) usage
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$API_CODE" = "" ];then
    if [ -s $SAVE_API_CODE ];then
        API_CODE=`cat $SAVE_API_CODE`
    else
        usage
        exit 1
    fi
fi

if [ "$1" = "" ]; then
    usage
    exit 1
fi

CW_API_CMD="$1"

case $CW_API_CMD in
    get-me)
        API_METH="GET"
        API_PATH="me"
        ;;
    get-rooms)
        API_METH="GET"
        API_PATH="rooms"
        ;;
    get-my-status)
        API_METH="GET"
        API_PATH="my/status"
        ;;
    post-mes)
        if [ "$ROOM_ID" = "" ];then
            if [ -s $SAVE_ROOM_ID ];then
                ROOM_ID=`cat $SAVE_ROOM_ID`
            else
                usage
                exit 1
            fi
        fi
        if [ "$2" = "" -o "$ROOM_ID" = "" ];then
            usage
            exit 1
        fi
        API_METH="POST"
        API_PATH="rooms/$ROOM_ID/messages"
        API_POST_MES=`echo $2 | ruby -r uri -ne 'print URI.escape $_'`
        ;;
    \?) usage
        exit 1
        ;;
esac

CURL_HD="-X $API_METH"
if [ "$CW_API_CMD" = "post-mes" ];then
    CURL_HD="$CURL_HD -d \"body=$API_POST_MES\""
fi

CURL_API_CODE="-H \"X-ChatWorkToken: $API_CODE\""

CURL_CMD="curl -s \
 $CURL_HD \
 $CURL_API_CODE \
 $ENDPOINT/$API_PATH"

CURL_RES=`eval $CURL_CMD`

type jq 2>&1 >/dev/null
if [ $? -eq 0 ];then
    echo $CURL_RES | jq "."
else
    echo $CURL_RES
fi

if [ "$IS_ONESHOT" != "1" ];then
    if [ "$API_CODE" != "" ];then
        echo "$API_CODE" > $SAVE_API_CODE
    fi
    if [ "$ROOM_ID" != "" ];then
        echo "$ROOM_ID" > $SAVE_ROOM_ID
    fi
fi

exit 0
